#!/usr/bin/env bash
set -euo pipefail

# Local Dev — Pay Platform Setup (wrapper)
#
# Seeds pay-platform with a council + PP config by exercising the admin API:
#   - Loads PAY_ADMIN keypair from .local-dev-keys (generated by setup-keys.sh)
#   - Loads council + PP info from .local-dev-state (written by setup-c + setup-pp)
#   - PAY_ADMIN authenticates to pay-platform → JWT
#   - Creates a council record via POST /admin/councils
#   - Creates a PP record via POST /admin/councils/:id/pps
#
# This is production-like — same admin API surface that a future admin console
# would use. If pay-platform's admin endpoints break, this script breaks too.
#
# Prerequisites:
#   - setup-keys.sh has been run (.local-dev-keys exists)
#   - up.sh has been run (pay-platform running with ADMIN_WALLETS set)
#   - setup-c.sh has been run (.local-dev-state has council + channel IDs)
#   - setup-pp.sh has been run (.local-dev-state has PP_PK + PROVIDER_URL)
#
# Usage:
#   ./setup-pay.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DENO_BIN="${DENO_BIN:-deno}"
command -v "$DENO_BIN" >/dev/null 2>&1 || DENO_BIN="$HOME/.deno/bin/deno"
command -v "$DENO_BIN" >/dev/null 2>&1 || {
  echo "ERROR: deno not found. Run up.sh first or install Deno." >&2
  exit 1
}

# Load PAY_ADMIN keypair from .local-dev-keys
KEYS_FILE="$SCRIPT_DIR/.local-dev-keys"
if [ ! -f "$KEYS_FILE" ]; then
  echo "ERROR: $KEYS_FILE not found. Run setup-keys.sh first." >&2
  exit 1
fi
PAY_ADMIN_PK=$(grep "^PAY_ADMIN_PK=" "$KEYS_FILE" | cut -d= -f2)
PAY_ADMIN_SK=$(grep "^PAY_ADMIN_SK=" "$KEYS_FILE" | cut -d= -f2)
if [ -z "$PAY_ADMIN_PK" ] || [ -z "$PAY_ADMIN_SK" ]; then
  echo "ERROR: PAY_ADMIN_PK or PAY_ADMIN_SK missing from $KEYS_FILE" >&2
  exit 1
fi

export PAY_ADMIN_PK PAY_ADMIN_SK

cd "$SCRIPT_DIR"
exec "$DENO_BIN" run --allow-all setup-pay.ts "$@"
