#!/usr/bin/env bash
set -euo pipefail

# setup-keys.sh — generates deterministic keypairs for all local-dev roles.
#
# Run ONCE after up.sh, before any setup-* script. The keypairs are stable
# across down/up cycles (derived from fixed seeds) so that up.sh can
# reference them in service configs like ADMIN_WALLETS.
#
# Roles:
#   DEPLOYER  — deploys Soroban contracts (used by setup-c.sh)
#   PAY_ADMIN — configures pay-platform councils (used by setup-pay.sh)
#
# Output: .local-dev-keys file consumed by up.sh and setup-* scripts.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SHARED_FILE="$SCRIPT_DIR/.local-dev-keys"
DENO_BIN="${DENO_BIN:-$(command -v deno 2>/dev/null || echo "$HOME/.deno/bin/deno")}"

GREEN='\033[0;32m'
NC='\033[0m'
info() { echo -e "${GREEN}[INFO]${NC} $*"; }

# Generate deterministic keypairs using fixed seeds.
# Each role gets a unique seed → SHA-256 → Stellar keypair.
"$DENO_BIN" eval "
import { Keypair } from 'npm:@stellar/stellar-sdk@14.2.0';

// Deterministic: same seed → same keypair every time.
// These are local-dev only — not secrets.
async function deterministicKeypair(seed) {
  const hash = new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(seed)));
  return Keypair.fromRawEd25519Seed(hash);
}

const deployer = await deterministicKeypair('moonlight-local-dev-deployer-admin-v1');
const payAdmin = await deterministicKeypair('moonlight-local-dev-pay-admin-v1');

const lines = [
  '# Generated by setup-keys.sh — deterministic keypairs for local-dev roles.',
  '# Stable across down/up cycles. Consumed by up.sh and setup-* scripts.',
  '# Created: ' + new Date().toISOString(),
  '',
  '# Contract deployer admin (used by setup-c.sh)',
  'DEPLOYER_PK=' + deployer.publicKey(),
  'DEPLOYER_SK=' + deployer.secret(),
  '',
  '# Pay-platform admin (used by setup-pay.sh, referenced in ADMIN_WALLETS)',
  'PAY_ADMIN_PK=' + payAdmin.publicKey(),
  'PAY_ADMIN_SK=' + payAdmin.secret(),
];

console.log(lines.join('\n'));
" > "$SHARED_FILE"

info "Shared keypairs written to $SHARED_FILE"
cat "$SHARED_FILE" | grep "_PK=" | while IFS= read -r line; do
  info "  $line"
done
