/**
 * Section 03a — Alice opens browser-wallet, deposits, opens Send form.
 *
 * Demo beats:
 *   1. Alice opens browser-wallet for the first time
 *   2. Sets a password, imports her 12-word mnemonic
 *   3. Toggles to private view, creates the privacy channel
 *   4. Adds the privacy provider, connects (signs SEP-10 challenge)
 *   5. Deposits XLM into the channel via the Ramp form
 *   6. Opens the Send form and (best-effort) sends to BOB_MLXDR if present
 *
 * NOTE: Send requires Bob's MLXDR (generated by Section 03b's Receive flow).
 * If BOB_MLXDR is absent in run.env, the spec stops after opening the Send
 * form so the recording still captures Alice's send-screen interaction.
 */
import { test } from "@playwright/test";
import { loadRunEnv, readRunArtifact, requireValue } from "../helpers/run-env";
import {
  closeWalletContext,
  launchWalletContext,
} from "../fixtures/wallet-context";
import {
  addAndConnectProvider,
  createPrivacyChannel,
  deposit,
  findBrowserWalletExtensionId,
  onboardWithMnemonic,
  openWalletPopup,
  selectCustomNetwork,
  send,
  toggleToPrivateView,
} from "../fixtures/browser-wallet";

const RECORDING_PASSWORD = "recording";

test.describe.configure({ mode: "serial" });

test("03a — Alice deposit + send", async () => {
  const env = loadRunEnv();
  const channelId = requireValue(env, "PRIVACY_CHANNEL_ID");

  const handle = await launchWalletContext({
    section: "03a",
    runId: env.RUN_ID,
    profileName: "alice",
  });

  try {
    const extensionId = await findBrowserWalletExtensionId(handle.context);
    const wallet = await openWalletPopup(handle.context, extensionId);

    await onboardWithMnemonic(wallet, {
      password: RECORDING_PASSWORD,
      mnemonic: env.ALICE_MNEMONIC,
    });

    await selectCustomNetwork(wallet);

    await toggleToPrivateView(wallet);

    await createPrivacyChannel(wallet, {
      contractId: channelId,
      channelName: "Moonlight Demo Council",
      network: "Custom",
      assetCode: "XLM",
    });

    await addAndConnectProvider(wallet, {
      providerUrl: env.PROVIDER_PLATFORM_URL,
      providerName: "Acme Privacy Provider",
      password: RECORDING_PASSWORD,
    });

    await deposit(wallet, { amount: "100" });

    const bobMlxdr = readRunArtifact("bob-mlxdr");
    if (bobMlxdr && bobMlxdr.trim().length > 0) {
      await send(wallet, {
        receiverMlxdr: bobMlxdr,
        amount: "25",
      });
    }
  } finally {
    await closeWalletContext(handle);
  }
});
