/**
 * Manages a provider-platform instance for local dev lifecycle testing.
 * Starts PostgreSQL, writes config, runs migrations, and starts the provider from source.
 *
 * In CI, docker-compose handles this instead (see docker-compose.yml).
 */

const PG_CONTAINER = "lifecycle-e2e-db";
const PG_PORT = 5452;
const PG_DB = "lifecycle_e2e_db";
const PG_USER = "admin";
const PG_PASS = "devpass";
const PROVIDER_PORT = 3030;

export interface ProviderInstance {
  url: string;
  stop: () => Promise<void>;
}

export interface ProviderStartOptions {
  providerPlatformPath: string;
  rpcUrl: string;
  channelContractId: string;
  channelAuthId: string;
  assetContractId: string;
  providerSecretKey: string;
  treasuryPublicKey: string;
  treasurySecretKey: string;
}

export async function startProvider(
  opts: ProviderStartOptions,
): Promise<ProviderInstance> {
  const { providerPlatformPath } = opts;
  const databaseUrl =
    `postgresql://${PG_USER}:${PG_PASS}@localhost:${PG_PORT}/${PG_DB}`;

  // 1. Start PostgreSQL
  console.log("  Starting PostgreSQL...");
  await ensurePostgres();

  // 2. Back up existing .env and write ours
  const envBackup = await backupAndWriteEnv(opts, databaseUrl);

  // 3. Install deps (idempotent)
  await run("deno", ["install"], providerPlatformPath, "install deps");

  // 4. Run migrations
  console.log("  Running migrations...");
  await run(
    "deno",
    ["-A", "--node-modules-dir", "npm:drizzle-kit", "migrate"],
    providerPlatformPath,
    "migrations",
  );

  // 5. Start provider-platform
  console.log("  Starting provider-platform...");
  const child = new Deno.Command("deno", {
    args: ["run", "--allow-all", "--unstable-kv", "src/main.ts"],
    cwd: providerPlatformPath,
    stdout: "piped",
    stderr: "piped",
  }).spawn();

  // Drain stdout to log file
  const logPath = new URL("./provider.log", import.meta.url).pathname;
  const logFile = await Deno.open(logPath, {
    write: true,
    create: true,
    truncate: true,
  });
  const logWriter = logFile.writable.getWriter();
  child.stdout
    .pipeTo(
      new WritableStream({
        write(chunk) {
          return logWriter.write(chunk);
        },
      }),
    )
    .catch(() => {});
  child.stderr
    .pipeTo(new WritableStream({ write() {} }))
    .catch(() => {});

  // 6. Wait for ready
  const url = `http://localhost:${PROVIDER_PORT}`;
  await waitForReady(url);
  console.log(`  Provider ready at ${url} (log: ${logPath})`);

  return {
    url,
    async stop() {
      try {
        child.kill("SIGTERM");
      } catch { /* already dead */ }
      try {
        await child.status;
      } catch { /* ignore */ }
      try {
        logWriter.close();
      } catch { /* ignore */ }
      await restoreEnv(providerPlatformPath, envBackup);
      await stopPostgres();
    },
  };
}

// ── PostgreSQL ────────────────────────────────────────────────────

async function ensurePostgres(): Promise<void> {
  const check = await docker([
    "ps",
    "--filter",
    `name=^${PG_CONTAINER}$`,
    "--format",
    "{{.Names}}",
  ]);

  if (decode(check.stdout).trim() === PG_CONTAINER) {
    console.log("  PostgreSQL already running");
    return;
  }

  await docker(["rm", "-f", PG_CONTAINER]);

  const start = await docker([
    "run", "-d", "--name", PG_CONTAINER,
    "-p", `${PG_PORT}:5432`,
    "-e", `POSTGRES_USER=${PG_USER}`,
    "-e", `POSTGRES_PASSWORD=${PG_PASS}`,
    "-e", `POSTGRES_DB=${PG_DB}`,
    "postgres:18",
  ]);

  if (!start.success) {
    throw new Error(
      `Failed to start PostgreSQL: ${decode(start.stderr)}`,
    );
  }

  for (let i = 0; i < 30; i++) {
    const ready = await docker([
      "exec", PG_CONTAINER, "pg_isready", "-U", PG_USER,
    ]);
    if (ready.success) {
      console.log("  PostgreSQL ready");
      return;
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  throw new Error("PostgreSQL did not become ready after 30s");
}

async function stopPostgres(): Promise<void> {
  await docker(["rm", "-f", PG_CONTAINER]);
}

// ── .env management ──────────────────────────────────────────────

async function backupAndWriteEnv(
  opts: ProviderStartOptions,
  databaseUrl: string,
): Promise<string | null> {
  const envPath = `${opts.providerPlatformPath}/.env`;
  let backupPath: string | null = null;

  try {
    const existing = await Deno.readTextFile(envPath);
    backupPath = `${envPath}.lifecycle-backup`;
    await Deno.writeTextFile(backupPath, existing);
  } catch {
    // No existing .env
  }

  const content = `# Generated by lifecycle E2E test — will be restored after test
PORT=${PROVIDER_PORT}
MODE=development
LOG_LEVEL=WARN
SERVICE_DOMAIN=localhost

DATABASE_URL=${databaseUrl}

NETWORK=local
STELLAR_RPC_URL=${opts.rpcUrl}
NETWORK_FEE=1000000000
CHANNEL_CONTRACT_ID=${opts.channelContractId}
CHANNEL_AUTH_ID=${opts.channelAuthId}
CHANNEL_ASSET_CODE=XLM
CHANNEL_ASSET_CONTRACT_ID=${opts.assetContractId}

PROVIDER_SK=${opts.providerSecretKey}
OPEX_PUBLIC=${opts.treasuryPublicKey}
OPEX_SECRET=${opts.treasurySecretKey}

SERVICE_AUTH_SECRET=
SERVICE_FEE=100
CHALLENGE_TTL=900
SESSION_TTL=21600

MEMPOOL_SLOT_CAPACITY=100
MEMPOOL_EXPENSIVE_OP_WEIGHT=10
MEMPOOL_CHEAP_OP_WEIGHT=1
MEMPOOL_EXECUTOR_INTERVAL_MS=5000
MEMPOOL_VERIFIER_INTERVAL_MS=10000
MEMPOOL_TTL_CHECK_INTERVAL_MS=60000
`;

  await Deno.writeTextFile(envPath, content);
  return backupPath;
}

async function restoreEnv(
  providerPath: string,
  backupPath: string | null,
): Promise<void> {
  const envPath = `${providerPath}/.env`;
  if (backupPath) {
    try {
      const content = await Deno.readTextFile(backupPath);
      await Deno.writeTextFile(envPath, content);
      await Deno.remove(backupPath);
    } catch { /* best effort */ }
  } else {
    try {
      await Deno.remove(envPath);
    } catch { /* ignore */ }
  }
}

// ── Helpers ──────────────────────────────────────────────────────

async function docker(args: string[]): Promise<Deno.CommandOutput> {
  return new Deno.Command("docker", {
    args,
    stdout: "piped",
    stderr: "piped",
  }).output();
}

function decode(buf: Uint8Array): string {
  return new TextDecoder().decode(buf);
}

async function run(
  cmd: string,
  args: string[],
  cwd: string,
  label: string,
): Promise<void> {
  const result = await new Deno.Command(cmd, {
    args,
    cwd,
    stdout: "piped",
    stderr: "piped",
  }).output();

  if (!result.success) {
    throw new Error(`${label} failed:\n${decode(result.stderr)}`);
  }
}

async function waitForReady(
  url: string,
  timeoutMs = 60_000,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      await fetch(
        `${url}/api/v1/stellar/auth?account=GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF`,
      );
      return;
    } catch {
      // Not ready yet
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  throw new Error(`Provider not ready after ${timeoutMs}ms`);
}
