/**
 * Inject the council-platform API URL into the network-dashboard's runtime
 * config so the council list / detail / transaction views surface the real
 * council during the section 04 recording.
 *
 * The dashboard does NOT take an embedded `councils:` array — it reads
 * `councilPlatformUrl` from `window.__DASHBOARD_CONFIG__` and fetches
 * `${councilPlatformUrl}/api/v1/public/councils` at page load
 * (see network-dashboard/src/lib/config.ts → getCouncils()).
 *
 * `local-dev/up.sh` writes a `public/config.js` with no councilPlatformUrl —
 * the dashboard would otherwise render "No councils registered yet". The
 * dashboard server (`network-dashboard/src/server.ts`) serves `public/`
 * directly, so rewriting `config.js` is sufficient — no rebuild required.
 *
 * Path resolution: the user runs multiple local-dev stacks side-by-side
 * (pw-video-eval, full-stack, etc.), each pointing at its own
 * network-dashboard checkout. The dashboard our recording connects to may
 * not be the one launched from this checkout — so the helper inspects the
 * process bound to the dashboard's port (`lsof -i :PORT`) and writes to
 * THAT process's CWD. Falls back to `NETWORK_DASHBOARD_PATH` env var, then
 * `~/repos/network-dashboard`.
 */
import fs from "fs";
import os from "os";
import path from "path";
import { execSync } from "child_process";
import process from "node:process";

export interface DashboardConfigOptions {
  /** council-platform API URL — the dashboard fetches /api/v1/public/councils from this. */
  councilPlatformUrl: string;
  rpcUrl?: string;
  horizonUrl?: string;
  stellarRpcPort?: string; // used when rpcUrl/horizonUrl unset
  /** Override the dashboard repo path; otherwise auto-detect via probeUrl. */
  dashboardPath?: string;
  /** URL of the live dashboard — used to find the serving process's CWD. */
  probeUrl?: string;
}

/**
 * Inspect the process bound to `port` and return its CWD if we can find a
 * `public/` dir below it (i.e. it's the dashboard server). Returns
 * undefined if anything goes wrong.
 */
function dashboardCwdFromPort(port: number): string | undefined {
  try {
    const lsof = execSync(`lsof -nP -i :${port} -sTCP:LISTEN -t`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    const pid = lsof.split("\n")[0];
    if (!pid) return undefined;
    // -a ANDs the filters; -p PID + -d cwd narrows to that one fd.
    // Output for our PID: `p<pid>\nfcwd\nn<path>`.
    const cwdLine = execSync(`lsof -a -p ${pid} -d cwd -Fn`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    const lines = cwdLine.split("\n");
    const nLine = lines.find((l) => l.startsWith("n") && l.length > 1);
    const cwd = nLine?.slice(1).trim();
    if (!cwd) return undefined;
    if (fs.existsSync(path.join(cwd, "public"))) return cwd;
    return undefined;
  } catch {
    return undefined;
  }
}

function portFromUrl(url: string | undefined): number | undefined {
  if (!url) return undefined;
  try {
    const u = new URL(url);
    if (u.port) return Number(u.port);
    return u.protocol === "https:" ? 443 : 80;
  } catch {
    return undefined;
  }
}

function resolveDashboardPath(opts: DashboardConfigOptions): string {
  if (opts.dashboardPath) return opts.dashboardPath;

  const fromEnv = process.env.NETWORK_DASHBOARD_PATH;
  if (fromEnv) return fromEnv;

  const port = portFromUrl(opts.probeUrl);
  if (port !== undefined) {
    const fromProcess = dashboardCwdFromPort(port);
    if (fromProcess) return fromProcess;
  }

  return path.join(os.homedir(), "repos", "network-dashboard");
}

function renderConfig(opts: DashboardConfigOptions): string {
  const port = opts.stellarRpcPort ?? "8000";
  const rpcUrl = opts.rpcUrl ?? `http://localhost:${port}/soroban/rpc`;
  const horizonUrl = opts.horizonUrl ?? `http://localhost:${port}`;

  return [
    `// Runtime configuration — regenerated by recording rig (section 04).`,
    `window.__DASHBOARD_CONFIG__ = ${
      JSON.stringify(
        {
          environment: "development",
          stellarNetwork: "standalone",
          rpcUrl,
          horizonUrl,
          councilPlatformUrl: opts.councilPlatformUrl,
        },
        null,
        2,
      )
    };`,
    ``,
  ].join("\n");
}

/**
 * Overwrite the dashboard's `public/config.js` so the council fetched from
 * `councilPlatformUrl` shows up. Returns the absolute path that was
 * written, for logging.
 */
export function writeDashboardConfig(opts: DashboardConfigOptions): string {
  const dashboardRoot = resolveDashboardPath(opts);
  const target = path.join(dashboardRoot, "public", "config.js");
  if (!fs.existsSync(path.dirname(target))) {
    throw new Error(
      `Dashboard public/ not found at ${dashboardRoot}/public — set ` +
        `NETWORK_DASHBOARD_PATH if the repo lives elsewhere.`,
    );
  }
  fs.writeFileSync(target, renderConfig(opts));
  return target;
}
